export const commentary = {
  0: [
    "Dot ball! Good tight delivery, the batter can’t find the gap.",
    "Excellent bowling on that occasion, no run added to the total.",
    "Defended solidly back to the bowler, pressure continues to build.",
    "Beaten outside off! The batter had no answer to that delivery.",
    "Straight to the fielder and they’ll get nothing from it.",
    "Watchful batting there, carefully played but no run available.",
    "The bowler keeps things nice and tight, another dot ball.",
    "Sharp fielding inside the circle cuts off any chance of a single.",
    "Nicely bowled into the channel, batter forced onto the back foot.",
    "Good discipline from the bowling side, they’re building pressure here.",
    "Tapped gently towards point but the fielder is quick to it.",
    "The batter wanted a run there for a moment, but wisely sent back.",
    "A probing delivery outside off stump, left alone comfortably.",
    "Short of a length and defended cautiously, no room to score.",
    "That one rushed onto the batter and all they could do was block it.",
    "Another excellent delivery, the fielders are right on top of the batter.",
    "Driven firmly but straight to cover, no run there at all.",
    "Tidy cricket from the bowling unit, not giving away anything easy."
  ],

  1: [
    "Quick single taken! Good awareness between the wickets.",
    "Tapped softly into the gap and they’ll comfortably get one.",
    "Easy rotation of strike, smart batting under pressure.",
    "Just a single, but every run matters in this situation.",
    "Worked away nicely towards square leg for a run.",
    "Guided down to third man and they’ll collect a single.",
    "Soft hands from the batter, they steal a quick run there.",
    "Pushed gently towards mid-on and they move through swiftly.",
    "Good communication between the batters, no hesitation there.",
    "Placed delicately into the gap for a simple single.",
    "The batter keeps the scoreboard ticking with another run.",
    "Neatly tucked off the pads and they jog through for one.",
    "A risky single attempted, but they make it home safely.",
    "Driven towards long-off and they settle for a single.",
    "Calm batting under pressure, rotating strike effectively.",
    "The field was up and they smartly take advantage with one run.",
    "A gentle push into the off side and they scamper through quickly.",
    "Nicely played with soft hands, ensuring an easy single."
  ],

  2: [
    "Excellent running between the wickets, they’ll come back for two.",
    "Well placed shot into the deep and the batters run hard.",
    "That was beautifully timed and they comfortably pick up a couple.",
    "Great commitment from both batters, turning one into two.",
    "Driven wide of the fielder and they hustle back for the second.",
    "Aggressive running there, putting pressure on the fielders.",
    "Good placement into the outfield allows them to collect two runs.",
    "Sharp work between the wickets, they never looked in trouble.",
    "The throw comes in late and they make the second easily.",
    "Clipped nicely off the legs and they race back for another.",
    "Strong running effort! The fitness levels are on display here.",
    "The fielders were a little slow getting to the ball and they capitalize.",
    "Punched through the covers and they return comfortably for two.",
    "Quick turn at the striker’s end ensures they complete the second.",
    "Excellent awareness from the batting pair, good cricket all around.",
    "That was hit into a big gap and they make full use of it.",
    "Nicely worked into the deep and they collect two valuable runs.",
    "Brilliant placement combined with energetic running between the wickets."
  ],

  3: [
    "Outstanding running! They push hard and complete three runs.",
    "Excellent commitment from both batters, turning it into three.",
    "The ball rolled deep into the outfield and they come back again.",
    "That’s brilliant awareness and fitness on display from the batting side.",
    "Huge gap in the field and they take full advantage with three runs.",
    "Aggressive running between the wickets, the crowd appreciates that effort.",
    "The fielders were slow to recover and the batters make them pay.",
    "Terrific placement and even better running earns them three.",
    "The chase from the fielder wasn’t quick enough and they complete three.",
    "Fantastic effort from both batters, they never stopped running.",
    "The throw comes in late and the third run is completed safely.",
    "Driven beautifully into the deep and they run all three comfortably.",
    "That required real fitness and determination, excellent cricket.",
    "Brilliant judgment from the batters to recognize the opportunity for three.",
    "Hard running puts pressure on the fielding side once again.",
    "That was not an easy three, but they worked incredibly hard for it.",
    "Wonderful awareness of the field placement allows them to collect three.",
    "A rare triple in modern cricket, and the crowd loves it."
  ],

  4: [
    "FOUR! Cracked beautifully through the covers, no stopping that.",
    "What a glorious boundary! Timed to absolute perfection.",
    "Driven majestically down the ground and away for four runs.",
    "That raced to the fence in no time at all, brilliant shot.",
    "Short and punished! The batter puts it away with authority.",
    "Elegant stroke play from the batter, pure class on display.",
    "Pierced the field perfectly and the ball rockets away to the boundary.",
    "A classy cover drive and the crowd erupts in appreciation.",
    "That was hit with exquisite timing, no chance for the fielders.",
    "FOUR more! The batter is finding the gaps with ease now.",
    "Beautifully placed behind point and it races away to the ropes.",
    "The bowler overpitched slightly and gets punished immediately.",
    "Delicate touch combined with perfect timing brings another boundary.",
    "That’s a trademark cricket shot, absolutely textbook stuff.",
    "The batter leans into the drive and sends it screaming to the fence.",
    "Superb placement! Split the fielders perfectly for four runs.",
    "Picked up off the pads and dispatched fine for a boundary.",
    "Pure elegance from the batter, that shot deserved four."
  ],

  6: [
    "SIX! That’s been launched high and handsome into the stands!",
    "Massive hit! The crowd erupts as the ball disappears into the night sky.",
    "Clean strike from the batter and it sails well beyond the boundary.",
    "What a shot! That’s gone a long, long way.",
    "Picked the length early and absolutely smashed it for six.",
    "Into the crowd it goes! The batter is dealing in maximums now.",
    "That was struck with incredible power and timing.",
    "Huge hit down the ground, the bowler can only watch helplessly.",
    "The batter stands tall and sends that delivery over the ropes with ease.",
    "A monstrous six! That nearly left the stadium.",
    "That’s gone straight into the second tier, unbelievable striking.",
    "The sound off the bat told the whole story, massive maximum.",
    "Short ball punished brutally, that disappeared in a flash.",
    "The batter clears the front leg and launches it deep into the stands.",
    "What incredible power from the batter, that’s a gigantic hit.",
    "No chance for any fielder there, that was always heading out of the ground.",
    "The crowd is loving this batting masterclass, another huge six.",
    "Absolutely hammered! That ball had wings on it."
  ],

  wicket: [
    "OUT! Clean bowled! The stumps are shattered and the batter has to walk back.",
    "Huge wicket for the bowling side and the crowd erupts in celebration.",
    "CAUGHT! Safe hands in the deep and the batter departs.",
    "TIMBER! The bowler completely outfoxed the batter there.",
    "LBW! Big appeal and the umpire raises the finger immediately.",
    "Gone! That’s a massive breakthrough at a crucial moment in the game.",
    "Edges it behind and the keeper makes no mistake whatsoever.",
    "The batter tried to go big but holes out straight to the fielder.",
    "Excellent bowling strategy finally pays off with a wicket.",
    "Dragged it back onto the stumps, the batter looks disappointed.",
    "Caught at cover! Sharp reflexes from the fielder inside the ring.",
    "A soft dismissal and the batting side loses an important wicket.",
    "That’s a brilliant catch under pressure, outstanding fielding effort.",
    "The bowler has been threatening for a while and finally gets rewarded.",
    "A massive moment in the match as the batter heads back to the pavilion.",
    "The slower ball does the trick and the batter mistimes it completely.",
    "Straight up in the air! The fielder settles under it comfortably.",
    "That could be a game-changing wicket for the bowling team."
  ],

  noball: [
    "No-ball called! The bowler has overstepped and that’s an extra run.",
    "Free hit coming up next ball, huge opportunity for the batting side.",
    "The umpire stretches out the arm, it’s a no-ball.",
    "That’s poor discipline from the bowler, gifting away a free run.",
    "Overstepped by quite a margin there, the captain won’t be happy.",
    "A costly mistake from the bowler and now a free hit follows.",
    "Front foot just lands beyond the line and it’s called immediately.",
    "No-ball! The pressure eases slightly for the batting team.",
    "That delivery won’t count and the batter gets another chance.",
    "The bowler loses rhythm there and sends down an illegal delivery.",
    "Big moment in the over as the umpire signals a no-ball.",
    "Free hit incoming! The crowd senses something exciting could happen.",
    "That’s a momentum-shifting mistake from the bowling side.",
    "The batter survives thanks to the bowler overstepping.",
    "Careless error from the bowler and they’ll have to reload again.",
    "No-ball signaled and the batting side gladly accepts the bonus run."
  ],

  wide: [
    "Wide ball! That was far beyond the batter’s reach.",
    "The umpire spreads the arms, signaling a wide delivery.",
    "Wayward bowling there, gives away an extra run.",
    "Too far outside off stump and it’s called wide immediately.",
    "Down the leg side and the keeper can’t prevent the extra.",
    "That delivery slipped badly from the bowler’s control.",
    "Pressure causing mistakes now as another wide is bowled.",
    "The batter didn’t even think about playing at that one.",
    "That’s a loose delivery and the bowling side won’t want too many of those.",
    "Wide called! The line was completely wrong on that occasion.",
    "The bowler sprays it down the leg side for an easy extra.",
    "Another extra added to the total through poor bowling discipline.",
    "That one sailed well outside the tramline and is rightly called wide.",
    "The keeper has to dive across but cannot stop the wide.",
    "An unnecessary extra run conceded by the fielding side.",
    "The bowler will need to regroup quickly after that wayward delivery."
  ]
};